import { TagSectionType } from './types'

const tags: TagSectionType[] = [
  {
    name: 'Food',
    tags: [
      { name: 'chinese' },
      { name: 'korean' },
      { name: '🍕', emoji: true },
      { name: '🍣', emoji: true },
      { name: '🍔', emoji: true },
      { name: 'brunch' },
      { name: 'breakfast' },
      { name: 'froyo' },
      { name: 'thai' },
      { name: 'spicy' },
      { name: 'vegan' },
      { name: 'vegetarian' },
      { name: 'carnivore' },
      { name: 'idc stuff my face' },
    ],
  },
  {
    name: 'Drink',
    tags: [
      { name: '🍺', emoji: true },
      { name: 'natty light' },
      { name: 'IPAs' },
      { name: 'rum' },
      { name: 'vodka' },
      { name: 'tequila' },
      { name: 'whisky' },
      { name: 'wine' },
      { name: 'brandy' },
      { name: 'gin' },
      { name: 'baijiu' },
      { name: 'sake' },
      { name: 'soju' },
      { name: 'scotch' },
      { name: 'fireball' },
      { name: 'cocktails' },
      { name: 'ethanol' },
      { name: 'rubinoff' },
    ],
  },
  {
    name: 'Tufts',
    tags: [
      { name: 'club president' },
      { name: 'acapella' },
      { name: 'meme royalty' },
      { name: 'dewick' },
      { name: 'carm' },
      { name: 'hodgdon' },
      { name: 'mugar' },
      { name: 'MCATs' },
      { name: 'musical theater' },
      { name: 'double major' },
      { name: 'jobless af' },
      { name: 'dual-degree' },
      { name: 'quirky queen' },
      { name: 'halligan lyfe' },
      { name: 'greek' },
      { name: 'tisch lyfe' },
      { name: '5 year program' },
      { name: 'journalism' },
      { name: 'liberal arts' },
      { name: 'engineering' },
      { name: 'Fletcher wannabe' },
      { name: 'did porn to pay tuition' },
    ],
  },
  {
    name: 'relationships',
    tags: [
      { name: '🏳️‍🌈', emoji: true },
      { name: '👫', emoji: true },
      { name: '👬', emoji: true },
      { name: '👭', emoji: true },
      { name: 'taken af' },
      { name: 'single af' },
      { name: 'open relationship' },
      { name: 'poly' },
      { name: 'complicated' },
      { name: 'married' },
      { name: 'single' },
      { name: "it's cuffing szn" },
      { name: 'one night stands' },
      { name: 'I do CS' },
      { name: "can't afford a relationship" },
      { name: 'here for the memes' },
    ],
  },
  {
    name: 'Hobbies',
    tags: [
      { name: '420' },
      { name: 'swimming' },
      { name: 'hiking' },
      { name: 'netflix' },
      { name: 'traveling' },
      { name: 'clubbing' },
      { name: 'singing' },
      { name: 'powerlifting' },
      { name: 'running' },
      { name: 'dancing' },
      { name: 'fire-juggling' },
      { name: "I don't go outside" },
    ],
  },
  {
    name: 'Music',
    tags: [
      { name: 'Pop' },
      { name: 'rap' },
      { name: 'EDM' },
      { name: 'hip hop' },
      { name: 'folk' },
      { name: 'dubstep' },
      { name: 'soul' },
      { name: 'indie' },
      { name: 'metal' },
      { name: 'rock' },
      { name: 'alternative' },
      { name: 'classical' },
      { name: 'blues' },
      { name: 'jazz' },
      { name: 'punk' },
      { name: 'country' },
      { name: 'I collect vinyls' },
    ],
  },
  {
    name: 'Sports',
    tags: [
      { name: 'go pats' },
      { name: 'fuck the pats' },
    ],
  },
  {
    name: 'Misc',
    tags: [
      { name: 'team star wars' },
      { name: 'team star trek' },
      { name: 'team LOTR' },
      { name: 'NY-bound' },
      { name: 'SF-bound' },
      { name: 'BOS-bound' },
      { name: 'DC-bound' },
      { name: 'leaving the US' },
      { name: '2cool4school' },
      { name: 'the future scares me' },
      { name: 'add me on LinkedIn' },
    ],
  },
  {
    name: 'xxx',
    tags: [
      { name: 'bdsm (light)' },
      { name: 'bdsm (heavy)' },
      { name: '3some' },
      { name: "devil's 3some" },
      { name: "angel's 3some" },
      { name: 'thirsty af' },
      { name: 'butt stuff' },
      { name: 'swinging' },
      { name: 'spanking' },
      { name: 'role play' },
      { name: 'call me daddy' },
    ],
  },
]

export default tags
