import { TagSectionType } from './types'

const tags: TagSectionType[] = [
  {
    name: 'Food',
    tags: [
      { id: 0, name: 'chinese' },
      { id: 1, name: 'korean' },
      { id: 2, name: '🍕', emoji: true },
      { id: 3, name: '🍣', emoji: true },
      { id: 4, name: '🍔', emoji: true },
      { id: 5, name: 'brunch' },
      { id: 6, name: 'breakfast' },
      { id: 7, name: 'froyo' },
      { id: 8, name: 'thai' },
      { id: 9, name: 'spicy' },
      { id: 10, name: 'vegan' },
      { id: 11, name: 'vegetarian' },
      { id: 12, name: 'carnivore' },
      { id: 13, name: 'idc stuff my face' },
    ],
  },
  {
    name: 'Drink',
    tags: [
      { id: 14, name: '🍺', emoji: true },
      { id: 15, name: 'natty light' },
      { id: 16, name: 'IPAs' },
      { id: 17, name: 'rum' },
      { id: 18, name: 'vodka' },
      { id: 19, name: 'tequila' },
      { id: 20, name: 'whisky' },
      { id: 21, name: 'wine' },
      { id: 22, name: 'brandy' },
      { id: 23, name: 'gin' },
      { id: 24, name: 'baijiu' },
      { id: 25, name: 'sake' },
      { id: 26, name: 'soju' },
      { id: 27, name: 'scotch' },
      { id: 28, name: 'fireball' },
      { id: 29, name: 'cocktails' },
      { id: 30, name: 'ethanol' },
      { id: 31, name: 'rubinoff' },
    ],
  },
  {
    name: 'Tufts',
    tags: [
      { id: 32, name: 'club president' },
      { id: 33, name: 'acapella' },
      { id: 34, name: 'meme royalty' },
      { id: 35, name: 'dewick' },
      { id: 36, name: 'carm' },
      { id: 37, name: 'hodgdon' },
      { id: 38, name: 'mugar' },
      { id: 39, name: 'MCATs' },
      { id: 40, name: 'musical theater' },
      { id: 41, name: 'double major' },
      { id: 42, name: 'jobless af' },
      { id: 43, name: 'dual-degree' },
      { id: 44, name: 'quirky queen' },
      { id: 45, name: 'halligan lyfe' },
      { id: 46, name: 'greek' },
      { id: 47, name: 'tisch lyfe' },
      { id: 48, name: '5 year program' },
      { id: 49, name: 'journalism' },
      { id: 50, name: 'liberal arts' },
      { id: 51, name: 'engineering' },
      { id: 52, name: 'Fletcher wannabe' },
      { id: 53, name: 'did porn to pay tuition' },
    ],
  },
  {
    name: 'relationships',
    tags: [
      { id: 53, name: '🏳️‍🌈', emoji: true },
      { id: 54, name: '👫', emoji: true },
      { id: 55, name: '👬', emoji: true },
      { id: 56, name: '👭', emoji: true },
      { id: 57, name: 'taken af' },
      { id: 58, name: 'single af' },
      { id: 59, name: 'open relationship' },
      { id: 60, name: 'poly' },
      { id: 61, name: 'complicated' },
      { id: 62, name: 'married' },
      { id: 63, name: 'single' },
      { id: 64, name: "it's cuffing szn" },
      { id: 65, name: 'one night stands' },
      { id: 66, name: 'I do CS' },
      { id: 67, name: "can't afford a relationship" },
      { id: 68, name: 'here for the memes' },
    ],
  },
  {
    name: 'Hobbies',
    tags: [
      { id: 69, name: '420' },
      { id: 70, name: 'swimming' },
      { id: 71, name: 'hiking' },
      { id: 72, name: 'netflix' },
      { id: 73, name: 'traveling' },
      { id: 74, name: 'clubbing' },
      { id: 75, name: 'singing' },
      { id: 76, name: 'powerlifting' },
      { id: 77, name: 'running' },
      { id: 78, name: 'dancing' },
      { id: 79, name: 'fire-juggling' },
      { id: 80, name: "I don't go outside" },
    ],
  },
  {
    name: 'Music',
    tags: [
      { id: 81, name: 'Pop' },
      { id: 82, name: 'rap' },
      { id: 83, name: 'EDM' },
      { id: 84, name: 'hip hop' },
      { id: 85, name: 'folk' },
      { id: 86, name: 'dubstep' },
      { id: 87, name: 'soul' },
      { id: 88, name: 'indie' },
      { id: 89, name: 'metal' },
      { id: 90, name: 'rock' },
      { id: 91, name: 'alternative' },
      { id: 92, name: 'classical' },
      { id: 93, name: 'blues' },
      { id: 94, name: 'jazz' },
      { id: 95, name: 'punk' },
      { id: 96, name: 'country' },
      { id: 97, name: 'I collect vinyls' },
    ],
  },
  {
    name: 'Sports',
    tags: [
      { id: 98, name: 'go pats' },
      { id: 99, name: 'fuck the pats' },
    ],
  },
  {
    name: 'Misc',
    tags: [
      { id: 100, name: 'team star wars' },
      { id: 101, name: 'team star trek' },
      { id: 102, name: 'team LOTR' },
      { id: 103, name: 'NY-bound' },
      { id: 104, name: 'SF-bound' },
      { id: 105, name: 'BOS-bound' },
      { id: 106, name: 'DC-bound' },
      { id: 107, name: 'leaving the US' },
      { id: 108, name: '2cool4school' },
      { id: 109, name: 'the future scares me' },
      { id: 110, name: 'add me on LinkedIn' },
    ],
  },
  {
    name: 'xxx',
    tags: [
      { id: 111, name: 'bdsm (light)' },
      { id: 112, name: 'bdsm (heavy)' },
      { id: 113, name: '3some' },
      { id: 114, name: "devil's 3some" },
      { id: 115, name: "angel's 3some" },
      { id: 116, name: 'thirsty af' },
      { id: 117, name: 'butt stuff' },
      { id: 118, name: 'swinging' },
      { id: 119, name: 'spanking' },
      { id: 120, name: 'role play' },
      { id: 121, name: 'call me daddy' },
    ],
  },
]

export default tags
