export * from './requestVerification'
export * from './verifyEmail'
export * from './acceptCoC'
export * from './me'
export * from './swipe'
export * from './getAllUsers'
export * from './getUser'
export * from './updateBio'
export * from './updateImages'
export * from './updateName'
export * from './getTags'
export * from './setTags'
export { TokenService } from './Endpoint'
